In [27]:
import pandas as pd
import numpy as np

In [28]:
data = pd.read_csv('huggingface\Final_Augmented_dataset_Diseases_and_Symptoms.csv')

<>:1: SyntaxWarning: invalid escape sequence '\F'
<>:1: SyntaxWarning: invalid escape sequence '\F'
C:\Users\tridu\AppData\Local\Temp\ipykernel_21724\1779134011.py:1: SyntaxWarning: invalid escape sequence '\F'
  data = pd.read_csv('huggingface\Final_Augmented_dataset_Diseases_and_Symptoms.csv')


In [29]:
len(data['diseases'].unique())

773

In [30]:
data_set = data.drop_duplicates()

In [33]:
def binary_to_decimal(row):
    return int(''.join(row.astype(str)), 2)

data_set['Decimal'] = data_set.iloc[:, 1:].apply(binary_to_decimal, axis=1)

C:\Users\tridu\AppData\Local\Temp\ipykernel_21724\2499326450.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_set['Decimal'] = data_set.iloc[:, 1:].apply(binary_to_decimal, axis=1)


In [35]:
sort_data = data_set.sort_values(by='Decimal')

In [52]:
sort_data = sort_data.reset_index(drop=True)

In [66]:
len(sort_data)

189647

In [81]:
grouped_df = sort_data.groupby('Decimal')['diseases'].agg(lambda x: list(x)).reset_index()

# Đếm số lượng giá trị 'disease' khác nhau trong mỗi nhóm
grouped_df['unique_disease_count'] = grouped_df['diseases'].apply(lambda x: len(set(x)))

# Lọc các nhóm có ít nhất 2 giá trị 'disease' khác nhau
filtered_df = grouped_df[grouped_df['unique_disease_count'] >= 11].drop(columns='unique_disease_count')

# Chuyển danh sách giá trị 'disease' về dạng chuỗi phân cách bằng dấu phẩy
filtered_df['diseases'] = filtered_df['diseases'].apply(lambda x: ', '.join(sorted(set(x))))

KeyError: 0

In [84]:
filters = filtered_df.reset_index(drop=True)

In [85]:
print(filters['diseases'][0])

acariasis, allergy, contact dermatitis, dyshidrosis, eczema, food allergy, itching of unknown cause, onychomycosis, scabies, scarlet fever, viral exanthem


In [86]:
import torch

In [125]:
x = torch.tensor([[10, 9, 8, 7, 6, 5, 4, 3, 2, 1],[1,2,3,4,5,6,7,8,9,10]])
y = torch.tensor([[0,0,1,0,0],[0,0,0,1,0]])

x_arg = torch.argmax(x)

In [127]:
x_arg == torch.argmax(y,1)

tensor([False, False])

In [115]:
print(x_arg[1])

tensor([[0, 1, 2, 3, 4],
        [9, 8, 7, 6, 5]])


In [123]:
y_arg = torch.argmax(y, 1)

In [124]:
print(y_arg)

tensor([2, 3])


In [118]:
contains_b = torch.any(torch.eq(x_arg[1][0], y_arg[0]))

In [119]:
print(contains_b)

tensor(True)


In [130]:
import torch

# Tạo tensor A và B
A = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = torch.tensor([2, 2, 2])

# Lấy top 2 argmax của mỗi hàng của A
top2_indices = A.topk(2, dim=1).indices

# So sánh top 2 argmax của mỗi hàng của A với các giá trị tương ứng trong B
for i in range(A.shape[0]):
    print(top2_indices[i] == B[i])
    

tensor([ True, False])
tensor([ True, False])
tensor([ True, False])
